# Generated by Django 3.2.13 on 2022-05-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rout',
            name='distance_max',
            field=models.PositiveIntegerField(help_text='If range - enter max distance, else - leave empty', null=True),
        ),
        migrations.RemoveField(
            model_name='rout',
            name='direction',
        ),
        migrations.AddField(
            model_name='rout',
            name='direction',
            field=models.ManyToManyField(null=True, to='routs.Direction'),
        ),
        migrations.AlterField(
            model_name='rout',
            name='distance',
            field=models.PositiveIntegerField(help_text='Enter distance in kilometers, or min distance if range'),
        ),
    ]
