# Generated by Django 3.2.13 on 2022-05-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0002_auto_20220507_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='rout',
            name='is_transport_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rout',
            name='wallpaper_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
