# Generated by Django 3.2.13 on 2022-05-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0002_alter_availability_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rout',
            name='google_map_foreign_link',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rout',
            name='kommot_map_link',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
    ]
