# Generated by Django 3.2.13 on 2022-05-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0003_auto_20220521_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('rout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='routs.rout')),
            ],
        ),
    ]
