# Generated by Django 3.2.13 on 2022-05-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0003_auto_20220507_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rout',
            name='direction',
            field=models.ManyToManyField(to='routs.Direction'),
        ),
    ]
