# Generated by Django 3.2.13 on 2022-08-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserBehaviourData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(help_text='User idenitificator', null=True)),
                ('action_dttm', models.DateTimeField()),
                ('data', models.CharField(max_length=2048)),
                ('action_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routs.surface')),
            ],
        ),
    ]
