# Generated by Django 3.2.13 on 2022-05-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0004_alter_rout_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rout',
            name='wallpaper_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
