# Generated by Django 3.2.13 on 2022-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0005_alter_rout_wallpaper_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rout',
            name='distance_max',
            field=models.PositiveIntegerField(help_text='If range - enter max distance, else - enter 0', null=True),
        ),
    ]
