# Generated by Django 3.2.13 on 2022-08-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routs', '0005_useraction_userbehaviourdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehaviourdata',
            name='action_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routs.useraction'),
        ),
    ]
